Testing Feature Branch

diff --git a/.github/workflows/feature_branch_workflow.yaml b/.github/workflows/feature_branch_workflow.yaml
--- a/.github/workflows/feature_branch_workflow.yaml
+++ b/.github/workflows/feature_branch_workflow.yaml
@@ -24,6 +24,8 @@ env:
   TRUNK_BRANCH: main
   FEATURE_BRANCH: feature/${{github.event.inputs.feature_branch}}
   PR_EXIST: 'false'
+  PR_URL: ''
+  PR_HTML_URL: ''
 
 # Define jobs within the workflow
 jobs:
@@ -33,9 +35,6 @@ jobs:
     if: github.event.inputs.feature_branch != ''
     steps:
 
-      - name: Checkout Code Repository
-        uses: actions/checkout@v4
-
       - name: Get Pull Request
         id: getPRList
         uses: OmOmofonmwan/get-pr-number-based-off-branch-name@main
@@ -44,13 +43,17 @@ jobs:
           repository: ${{github.repository}}
           branch_name: ${{env.FEATURE_BRANCH}}
 
-      - name: Update PR_EXIST Environment Variable
+      - name: Update PR Environment Variables
         if: steps.getPRList.outputs.pr_exists == 'true'
-        run: echo "PR_EXIST=true" >> $GITHUB_ENV
+        run: |
+          echo "PR_EXIST=true" >> $GITHUB_ENV
+          echo "PR_URL=${{steps.getPRList.outputs.pr_url}}" >> $GITHUB_ENV
+          echo "PR_HTML_URL=${{steps.getPRList.outputs.pr_html_url}}" >> $GITHUB_ENV
   
   start_action:
     runs-on: ubuntu-latest
     name: Start Action - feature/${{github.event.inputs.feature_branch}}
+    needs: check_if_pr
     if: github.event.inputs.action == 'Start' 
 
     permissions:
@@ -58,6 +61,12 @@ jobs:
       pull-requests: write
 
     steps:
+      - name: If PR Exist
+        if: env.PR_EXIST == 'true'
+        run: |
+          echo "ERROR: Pull Request Already Exists For ${{env.FEATURE_BRANCH}}"
+          exit 1
+
       - name: Checkout Code Repository
         uses: actions/checkout@v4
 
@@ -72,7 +81,7 @@ jobs:
           echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
 
       - name: Print Version
-        run: echo ${{env.POM_VERSION}}
+        run: echo "Current Version - ${{env.POM_VERSION}}"
 
       - name: Split version code
         uses: xom9ikk/split@v1.1
@@ -96,37 +105,33 @@ jobs:
           git commit -am "Draft: Update feature version to ${{env.uniqueVersion}}"
           git push -u origin $FEATURE_BRANCH
 
-      # - name: Run the Action
-      #   uses: devops-infra/action-pull-request@v0.5.5
-      #   if: env.PR_EXIST == 'false'
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     source_branch: ${{env.FEATURE_BRANCH}}
-      #     target_branch: ikmdev::${{env.TRUNK_BRANCH}}
-      #     title: Draft - ${{env.FEATURE_BRANCH}}
-      #     body: "**Currently work in progress - ${{env.FEATURE_BRANCH}}**"
-      #     draft: true
-
       - name: Create PR 
         if: env.PR_EXIST == 'false'
         run: |
           curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{secrets.TOKEN}}" \
+              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
-             https://api.github.com/repos/BasedNoobDevelopers/${{github.event.repository.name}}/pulls \
+             https://api.github.com/repos/ikmdev/${{github.event.repository.name}}/pulls \
           -d '{"title":"Draft - ${{env.FEATURE_BRANCH}}","body":"Draft","head":"${{env.TRUNK_BRANCH}}","base":"${{github.repository}}:${{env.FEATURE_BRANCH}}"}'
 
   resume_action:
     runs-on: ubuntu-latest
     name: Resume Action - feature/${{github.event.inputs.feature_branch}}
-    if: github.event.inputs.action == 'Resume' && github.event.inputs.feature_branch != ''
+    if: github.event.inputs.action == 'Resume'
+    needs: check_if_pr
     permissions:
       contents: write
       pull-requests: write
 
     steps:
+      - name: If PR Does Not Exist
+        if: env.PR_EXIST == 'false'
+        run: |
+          echo "ERROR: Pull Request Does Not Exist For ${{env.FEATURE_BRANCH}}"
+          exit 1
+
       - name: Checkout Code Repository
         uses: actions/checkout@v4
 
@@ -180,12 +185,19 @@ jobs:
   finish_action:
     runs-on: ubuntu-latest
     name: Finish Action - feature/${{github.event.inputs.feature_branch}}
-    if: github.event.inputs.action == 'Finish' && github.event.inputs.feature_branch != ''
+    if: github.event.inputs.action == 'Finish'
+    needs: check_if_pr
     permissions:
       contents: write
       pull-requests: write
 
     steps:
+      - name: If PR Does Not Exist
+        if: env.PR_EXIST == 'false'
+        run: |
+          echo "ERROR: Pull Request Does Not Exist For ${{env.FEATURE_BRANCH}}"
+          exit 1
+          
       - name: Checkout Code Repository
         uses: actions/checkout@v4
 
@@ -200,7 +212,7 @@ jobs:
           echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
 
       - name: Print Version
-        run: echo ${{env.POM_VERSION}}
+        run: echo "Current Version - ${{env.POM_VERSION}}"
 
       - name: Split version code
         uses: xom9ikk/split@v1.1
@@ -225,21 +237,17 @@ jobs:
           git push origin $FEATURE_BRANCH
 
   update_pull_request:
-    needs: finish_action
+    needs: 
+      -  resume_action
+      -  finish_action
     runs-on: ubuntu-latest
     permissions:
       contents: write
       pull-requests: write
 
     steps:
-      - name: Get Pull Request
-        id: getPRList
-        uses: OmOmofonmwan/get-pr-number-based-off-branch-name@main
-        with:
-          github_token: ${{secrets.GITHUB_TOKEN}}
-          repository: ${{github.repository}}
-          branch_name: ${{env.FEATURE_BRANCH}}
-
+      - name: Print
+        run: echo ${{toJson(github)}}
       - name: Update PR
         if: steps.getPRList.outputs.pr_exists == 'true'
         run: |
@@ -254,42 +262,5 @@ jobs:
       - name: Set PR To Ready
         if: steps.getPRList.outputs.pr_exists == 'true'
         run: gh pr ready ${{steps.getPRList.outputs.pr_html_url}}
-        env:
-          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
-
-  
-
-  update_draft_pull_request:
-    needs: resume_action
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      pull-requests: write
-
-    steps:
-      - name: Get Pull Request
-        id: getPRList
-        uses: OmOmofonmwan/get-pr-number-based-off-branch-name@main
-        with:
-          github_token: ${{secrets.GITHUB_TOKEN}}
-          repository: ${{github.repository}}
-          branch_name: ${{env.FEATURE_BRANCH}}
-
-      - name: Update PR
-        if: steps.getPRList.outputs.pr_exists == 'true'
-        run: |
-          curl -L \
-           -X PATCH \
-           -H "Accept: application/vnd.github+json" \
-           -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
-           -H "X-GitHub-Api-Version: 2022-11-28" \
-           ${{steps.getPRList.outputs.pr_url}} \
-           -d '{"title":"Draft - ${{env.FEATURE_BRANCH}}","body":"Draft - ${{env.FEATURE_BRANCH}}","state":"open", "draft": "true"}'
-
-      - name: Set PR To Draft
-        if: steps.getPRList.outputs.pr_exists == 'true'
-        run: |
-          gh extension install kyanny/gh-pr-draft
-          gh pr ready --undo ${{steps.getPRList.outputs.pr_html_url}}
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
